version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: meal-plan-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meal_plan
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - meal-plan-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: meal-plan-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - meal-plan-network

networks:
  meal-plan-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
