#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Checking Prettier formatting..."
npx prettier --check "src/**/*.ts" "test/**/*.ts"

echo "🔍 Running ESLint check..."
npm run lint

echo "🔍 Running unit tests..."
npm run test

echo "🔍 Running e2e tests..."
npm run test:e2e:docker